application: jockey-player
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /
  static_files: index.html
  upload: index.html
  secure: always

  - url: /
  static_files: home.html
  upload: home.html
  secure: always

- url: /css
  static_dir: css
  secure: always

- url: /images
  static_dir: images
  secure: always

- url: /js
  static_dir: js
  secure: always

- url: /fonts
  static_dir: fonts
  secure: always


skip_files:
# Default patterns skipped by App Engine, which must be repeated since
# specifying skip_files overrides them otherwise.  See
# https://developers.google.com/appengine/docs/python/config/appconfig#Skipping_Files.
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
# Build files that have no effect in App Engine's runtime.
- ^.*\.MF$
- ^.*\.CMF$
- ^.*\.so$
- ^.*pywrap.+\.py$
- ^.*\.jslib$
